// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4yBAShYV41LftgJEO6Kno7r42vWkkxQ4',
    appId: '1:900340484787:web:ae417ea67333e40143bec6',
    messagingSenderId: '900340484787',
    projectId: 'alpersoraravci',
    authDomain: 'alpersoraravci.firebaseapp.com',
    databaseURL: 'https://alpersoraravci-default-rtdb.firebaseio.com',
    storageBucket: 'alpersoraravci.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZHh0y88fzyMX_LCGwDHwT8ScAF7pR55I',
    appId: '1:900340484787:android:2d301a25020ee23a43bec6',
    messagingSenderId: '900340484787',
    projectId: 'alpersoraravci',
    databaseURL: 'https://alpersoraravci-default-rtdb.firebaseio.com',
    storageBucket: 'alpersoraravci.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKoUwSKNOitP2cECVXHHlErjWb4FFrnNA',
    appId: '1:900340484787:ios:049de7ee23aa4bf643bec6',
    messagingSenderId: '900340484787',
    projectId: 'alpersoraravci',
    databaseURL: 'https://alpersoraravci-default-rtdb.firebaseio.com',
    storageBucket: 'alpersoraravci.appspot.com',
    iosBundleId: 'com.example.alperSoraravci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKoUwSKNOitP2cECVXHHlErjWb4FFrnNA',
    appId: '1:900340484787:ios:adcb4969cdd2c17843bec6',
    messagingSenderId: '900340484787',
    projectId: 'alpersoraravci',
    databaseURL: 'https://alpersoraravci-default-rtdb.firebaseio.com',
    storageBucket: 'alpersoraravci.appspot.com',
    iosBundleId: 'com.example.alperSoraravci.RunnerTests',
  );
}